services:
  postgres:
    image: postgres:latest
    container_name: maxvandam-db
    environment:
      POSTGRES_DB: maxvandam
      POSTGRES_USER: maxvandam_user
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
